<?php
//
//
// notice_vars.php
//
// DCForum+ Version 1.27
// September 30, 2009
//
//
//    This file is part of DCForum+
//
//    DCForum+ is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    DCForum+ is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with DCForum+; if not, write to the Free Software
//    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//
//
// only used for initial builiding
//

/////////////////////////////////
// registration message
/////////////////////////////////
$registration =  'Thank you for registering to use our forum. ';
$registration .= 'Following is your login information:' . "\n\n";
$registration .= '#MARKER#' . "\n\n";
$registration .= 'The forum is located at' . "\n\n";
$registration .= '#URL#' . "\n\n";
$registration .= 'Once there, click on login icon to begin using our ';
$registration .= 'forum. Once logged on, be sure to check out the user ';
$registration .= 'menu to view what options are you can set.' . "\n\n";
$registration .= 'Thank you.';


/////////////////////////////////
// forum subscription message
/////////////////////////////////
$forum_subscription =  'Thank you for subscribing to our forum.' . "\n\n";
$forum_subscription .= 'Following are new messages posted in the forums ';
$forum_subscription .= 'that you are subscribed to.  If you have any  ';
$forum_subscription .= 'questions or comments, please email us.' . "\n\n";
$forum_subscription .= 'Thank you again.';


/////////////////////////////////
// topic subscription message
/////////////////////////////////
$topic_subscription =  'A new message has been posted in the forum.' . "\n\n";
$topic_subscription .= '#MARKER#' . "\n\n";
$topic_subscription .= 'You receive this email because you asked to be notified ';
$topic_subscription .= 'of follow-up messages when you posted a message in this thread. ';
$topic_subscription .= 'This notification service informs you of new messages in ';
$topic_subscription .= 'the above mentioned thread only.' . "\n\n";
$topic_subscription .=  'Thank you for using our forum.';

/////////////////////////////////
// lost email message
/////////////////////////////////
$lost_password =  'This email is sent by DCForum Email retrieval system at' . "\n\n";
$lost_password .= '#URL#' . "\n\n";
$lost_password .= 'If you have not requested this service, please reply ';
$lost_password .= 'to this email and let the administrator  of the web site be aware.' . "\n\n";
$lost_password .= '#MARKER#' . "\n\n";
$lost_password .= 'Thank you.';


/////////////////////////////////
// account status message
/////////////////////////////////
$account_status =  'This email is generated by the forum program at' . "\n\n";
$account_status .= '#URL#' . "\n\n";
$account_status .= 'Following change has been made to your account:' . "\n\n";
$account_status .= '#MARKER#' . "\n\n";
$account_status .= 'Thank you.';


/////////////////////////////////
// private message email message
/////////////////////////////////
$private_message = 'This email is an automatic message generated by a forum program at' . "\n\n";
$private_message .= '#URL#' . "\n\n" . '#MARKER#' . "\n\n";
$private_message .= 'This email is sent to you because you requested an ';
$private_message .= 'email notification whenever you have a new message in your inbox.' . "\n\n";
$private_message .= 'Thank you.';

/////////////////////////////////
// email to a friend email message
/////////////////////////////////
$email_to_friend = 'Following email is from a friend using ';
$email_to_friend .= '"Email to a friend" feature at ' . "\n\n";
$email_to_friend .= '#URL#' . "\n\n";

/////////////////////////////////
// forum policy message
/////////////////////////////////
$forum_policy = 'The site administrator reserves the right to change 
the terms and conditions of the user agreement without
prior notice to the user. It is the responsibility of 
the user to regularly review the terms of this 
agreement.

The user agrees to the following terms

1. All information that you provide to us for your membership is correct.
2. You will not use your membership to spam, harrass, or exploit other members in any way.
3.  Vulgar, Abusive, Racist, and Sexist Language will not be tolerated.
4.  No mass posting or flooding of the boards is allowed.';


$notice_vars = array(

   'registration' => array(
      'subject' => 'Forum Registration Information',
      'desc' => '',
      'message' => $registration),


   'forum_subscription' => array(
       'subject' => 'Forum subscription notice',
       'desc' => '',
       'message' => $forum_subscription),


    'topic_subscription' => array(
          'subject' => 'Topic subscription email notification',
          'desc' => '',
          'message' => $topic_subscription),


   'lost_password' => array(
      'subject' => 'Forum account information request response',
      'desc' => '',
      'message' => $lost_password),


   'account_status' => array(
       'subject' => 'DCForum Account Status Report',
       'desc' => '',
       'message' => $account_status),


   'private_message' => array(
       'subject' => 'DCForum Notification: You have new message in your inbox',
       'desc' => '',
       'message' => $private_message),

   'email_to_friend' => array(
       'subject' => 'Email to a friend notification',
       'desc' => '',
       'message' => $email_to_friend),

   'forum_policy' => array(
      'subject' => 'Forum Acceptable Use Policy',
      'desc' => 'Please read the following forum acceptable use policy.
                 You must agree to the following terms in order to register
                 and use this forum.',
      'message' => $forum_policy),

);

?>
