<?php
////////////////////////////////////////////////////////////////////////
//
// setup_vars.php
//
// DCForum+ Version 1.27
// September 30, 2009
//
//
//    This file is part of DCForum+
//
//    DCForum+ is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    DCForum+ is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with DCForum+; if not, write to the Free Software
//    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//
//
//
// 	$Id: setup_vars.php,v 1.3 2005/03/26 18:12:17 david Exp $	
//

//
// ip filter pattern for use
// with block level
//
$ip_filter_pattern = array(

   '4' => 'nnn.nnn.nnn.nnn',
   '3' => 'nnn.nnn.nnn.***',
   '2' => 'nnn.nnn.***.***',
   '1' => 'nnn.***.***.***'

);

//
// date format hash
//
$date_format = array(
   '1' => 'US - Month/Day/Year',
   '2' => 'Europe - Day/Month/Year'
);



//
// main setup variable hash
//
$setup_vars = array(

   'time_zone' => array(
         'title' => 'Time zone',
         'desc' => 'Select default global time zone.
                    This is the default time zone if user has not selected
                    their own local time zone.',
         'value' => '1',
         'form' => 'select_plus'),

   'date_format' => array(
         'title' => 'Date Format',
         'desc' => 'NO LONGER USED',
         'value' => '1',
         'form' => 'select_plus'),

   'language' => array(
         'title' => 'Default lanuage',
         'desc' => 'Select default language - If other modules are installed, 
                    users will be able choose
                    from other language modules as well',
         'value' => '1',
         'form' => 'select_plus'),


   'auth_check_referer' =>
      array(
         'title' => 'Check HTTP referer before allowing certain functions?',
         'desc' => 'If \'yes\', remote postings will not be allowed.',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'session_duration' =>
      array(
         'title' => 'Session duration in minutes',
         'desc' => 'If a user session
                    is inactive for this period, the user is forced to login again.
                    This value should be at least 10 minutes.
                    If the user has set "Remain Logged in" option, however,
                    then this session is not affected.',
         'value' => '30',
         'form' => ''),

   'auth_allow_password_remembering' =>
      array(
         'title' => 'Extended login session option',
         'desc' => 'If you want to allow users to use "Remain logged on..." option,
                    set this option to "yes".',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'auth_allow_account_mod' =>
      array(
         'title' => 'Allow users to modify their account information?',
         'desc' => 'Set this option to "yes" if you want to allow your 
             registered users to change their account information.',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'auth_allow_password_mod' =>
      array(
         'title' => 'Allow users to change their password?',
         'desc' => 'Set this option to "yes" if you want to allow 
                your registered users to change their password.  If you 
                are using the email registration (wherein the password 
                is generated by the program), you may want to allow users
                to change their passwords to something easier to remember.',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'auth_allow_retrieve_password' =>
      array(
         'title' => 'Allow users to retrieve new password?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'auth_alert' =>
      array(
         'title' => 'Enable alert function?',
         'desc' => 'If \'yes\', users will be able to send alerts regarding
                    bad messages',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'hide_private' =>
      array(
         'title' => 'Hide restricted and private forums 
                     from users who do not have access?',
         'desc' => 'Restricted and private forums can only be accessed by
                    certain users.  If you want to hide them from the forum
                    listings, then select "yes".',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'auth_bad_word_list' =>
      array(
         'title' => 'Bad word list',
         'desc' => 'List bad words you wish to filter...each bad word 
               should be separated by a comma.',
         'value' => 'fuck,shit,tits,motherfuck,dick,blowjob',
         'form' => 'textarea|5|40|0'),

   'display_ip_address' =>
      array(
         'title' => 'Allow users to view IP address of other users?',
         'desc' => '',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'ip_blocking' =>
      array(
         'title' => 'Turn on IP blocking?',
         'desc' => '',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'ip_blocking_level' =>
      array(
         'title' => 'IP blocking pattern',
         'desc' => '',
         'value' => '4',
         'form' => 'select_plus'),


   'auth_admin_email_address' => 
      array(
         'title' => 'Administrator\'s email address',
         'desc' => '',
         'value' => 'you@yourdomain.com',
         'form' => ''),

   'admin_signature' =>
      array(
         'title' => 'Administrator\'s signature',
         'desc' => '',
         'value' => 'Forum administrator',
         'form' => ''),

   'name_length_max' =>
      array(
         'title' => 'Maximum length for username',
         'desc' => 'Maximum user name length',
         'value' => '15',
         'form' => ''),

   'auth_allow_registration' =>
      array(
         'title' => 'Allow users to register?',
         'desc' => 'Set this option to "yes" if you want users to be able to register
                   to use the forum.  If this option is "no", then no one can register.',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'auth_register_via_email' =>
      array(
         'title' => 'Enable email registeration?',
         'desc' => 'If this option is "yes", a randomly generated password will be emailed 
                    to the user requesting registration.  This option forces users 
                    to submit valid email addresses during registration.',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'auth_default_group' =>
      array(
         'title' => 'Default user group',
         'desc' => 'Group ID assigned to the user upon registration',
         'value' => '1',
         'form' => 'select_plus'),

   'auth_bad_emails' =>
      array(
         'title' => 'List of banned email domains',
         'desc' => 'List domain names of email services that you wish to reject for registration',
         'value' => 'hotmail.com,usa.net,iname.com,excitemail.com',
         'form' => ''),

   'auth_activate_user_on_registration' =>
      array(
         'title' => 'Activate user account upon registration?',
         'desc' => 'If "yes", user acccount will be active and they will be able to login.
                    Otherwise, the administrator must activate the account using the user manager.',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'auth_notify_admin_on_registration' =>
      array(
         'title' => 'Notifiy administrator when a new user registers?',
         'desc' => 'Select "yes" if you want to receive email notification when a 
                    new user registers to use the forum.',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'auth_notify_user_on_activation' =>
      array(
         'title' => 'Notify user when their account is activated?',
         'desc' => 'Select "yes" if you want to send an email notification to the user
                    whenever you change the account status',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'email_to_admin' =>
      array(
         'title' => 'Notify administrator if a new message is posted?',
         'desc' => 'Select "yes" if you want the administrator of the forum to receive an
                   email notification whenever a new message is posted.',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'email_to_mod' =>
      array(
         'title' => 'Notify forum moderator if a new message is posted?',
         'desc' => 'Select "yes" if you want the moderators of the forum to receive an
                   email notification whenever a new message is posted.',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),




   'auto_prune_forum_log' =>
      array(
         'title' => 'Forum log file limit (in days)',
         'desc' => 'To automatically remove old forum log entries, enter the
                    number of days of log entries you want to save.  This function
                    is automatically executed whenever a user logs in',
         'value' => '60',
         'form' => ''),

   'auto_prune_ip_log' => 
      array(
         'title' => 'IP log file limit (in days)',
         'desc' => 'To automatically remove old IP log entries, enter the number 
                    of days you want to save.  This function is executed whenever 
                    a user logs in.',
         'value' => '120',
         'form' => ''),

   'table_width' =>
      array(
         'title' => 'Table width',
         'desc' => 'Specify the table width.  Include percent sign if applicable.',
         'value' => '100%',
         'form' => ''),

   'read_count' =>
      array(
         'title' => 'Views option',
         'desc' => 'Select "yes" if you want to keep track of the 
                   number of times a topic has been read?',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'announcement_display_mode' =>
      array(
         'title' => 'Announcement display mode',
         'desc' => 'Select announcement display mode.  "list" will only list the subject.  "full"
                   will list the entire announcement.',
         'value' => 'list',
         'form' => 'radio|full|list|0'),

   'display_newest_user' =>
      array(
         'title' => 'Display "Welcome to our newest member..." link?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'display_num_users' =>
      array(
         'title' => 'Display the number of registered users in the forum listing page?',
         'desc' => 'Select yes if you want to display "nnn registered members" in the forum listings page',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'display_whos_online' =>
      array(
         'title' => 'Display "Who\'s online?" link in the forum listing page?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'team_icon' =>
      array(
         'title' => 'Icon for team users',
         'desc' => '',
         'value' => 'team_icon.gif',
         'form' => ''),

   'moderator_icon' =>
      array(
         'title' => 'Icon for moderators',
         'desc' => '',
         'value' => 'moderator_icon.gif',
         'form' => ''),

   'admin_icon' =>
      array(
         'title' => 'Icon for adminstrators',
         'desc' => '',
         'value' => 'admin_icon.gif',
         'form' => ''),

   'inactive_user_label' =>
      array(
         'title' => 'Label for users who are no longer in user database',
         'desc' => '',
         'value' => 'inactive user',
         'form' => ''),

   'inactive_user_icon' => 
      array(
         'title' => 'Icon for users who are no longer in user database',
         'desc' => '',
         'value' => 'inactive.gif',
         'form' => ''),

   'guest_label' =>
      array(
         'title' => 'Label for unregistered users',
         'desc' => '',
         'value' => 'Guest',
         'form' => ''),

   'guest_icon' =>
      array(
         'title' => 'Icon for unregistered users',
         'desc' => '',
         'value' => 'guest.gif',
         'form' => ''),


   'file_upload' =>
      array(
         'title' => 'Enable file attachments?',
         'desc' => 'If enabled, registered users will be able to upload attachements
                    with their messages',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'file_upload_size' =>
      array(
         'title' => 'If file upload is enabled, specify maximum file size in kBytes',
         'desc' => 'This is only a soft limit.  By default, PhP installation sets a hard limit
                    of 2MB.  If you want to allow file sizes greater
                    than 2MB, you need to consult your hosting company.',
         'value' => '50',
         'form' => ''),

   'file_upload_limit' =>
      array(
         'title' => 'If file upload is enabled, specify maximum number of files allowed per post',
         'desc' => 'For practical reasons, the maximum number of files as a hard limit of 10.',
         'value' => '1',
         'form' => ''),

   'file_upload_default' =>
      array(
         'title' => 'Default upload file type',
         'desc' => '',
         'value' => 'txt',
         'form' => 'select_plus'),
      
   'edit_allowed' =>
      array(
         'title' => 'Allow registered users to edit their message?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'edit_time_out' =>
      array(
         'title' => 'Edit time limit in minutes',
         'desc' => '',
         'value' => '60',
         'form' => ''),

   'html_allowed' =>
      array(
         'title' => 'For DCF text format, do you want to allow the use of HTML text?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'image_allowed' =>
      array(
         'title' => 'Allow users to embed images in the messages?',
         'desc' => 'This option displays image URLs as images.  This option
                    will only work if the URL linking is enabled.',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'subscription' =>
      array(
         'title' => 'Enable forum subscription?',
         'desc' => '',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'auto_send_subscription' =>
      array(
         'title' => 'When do you want to send subscription?',
         'desc' => 'Select from following choices',
         'value' => '',
         'form' => 'select_plus'),

   'email_notification' =>
      array(
         'title' => 'Enable topic subscription?',
         'desc' => '',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'allow_email_to_friend' =>
      array(
         'title' => 'Allow users to email  topics to a friend?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'allow_disable_profile' =>
      array(
         'title' => 'Allow users to hide their profiles?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'allow_disable_inbox' => 
      array(
         'title' => 'Allow users to disable their inbox system?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'allow_disable_email' => 
      array(
         'title' => 'Allow users to hide their email?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'user_rating' =>
      array(
         'title' => 'Allow registered users to rate each other?',
         'desc' => '',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'allow_disable_user_rating' => 
      array(
         'title' => 'Allow users not to participate in the user rating?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'topic_rating' =>
      array(
         'title' => 'Enable topic rating?',
         'desc' => '',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'allow_anyone_to_rate_topic' =>
      array(
         'title' => 'If topic rating is enabled, allow non-registered users to rate topics?',
         'desc' => '',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'topic_rating_threshold' =>
      array(
         'title' => 'Minimum number of votes before topic score is displayed',
         'desc' => '',
         'value' => '5',
         'form' => ''),

   'allow_avatar' =>
      array(
         'title' => 'Allow users to use avatar?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'allow_remote_avatar' =>
      array(
         'title' => 'Allow users to use remote image file as their avatar?',
         'desc' => '',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'allow_polls' =>
      array(
         'title' => 'Allow users to start polls?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'deny_poll_everyone' =>
      array(
         'title' => 'Only allow registered users to start polls?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),



   'expand_conference' =>
      array(
         'title' => 'Expand conference in the main listing?',
         'desc' => '',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'make_fully_threaded_list_default' =>
      array(
         'title' => 'Use fully threaded listing as the default?',
         'desc' => '',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

  'messages_per_page' =>
      array(
         'title' => 'Linear-style messages per page',
         'desc' => '',
         'value' => '10',
         'form' => ''),

   'use_icons' =>
      array(
         'title' => 'Use icons in the menu?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'use_text' =>
      array(
         'title' => 'Use text links in the menu?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'default_days' =>
      array(
         'title' => 'Default number of days for current topic listing',
         'desc' => 'The topic listing will only include those that are last modified
                    within this number of days.  User can also set a different value
                    using their menu.',
         'value' => '0',
         'form' => 'select_plus'),

   'mesg_max' =>
      array(
         'title' => 'Number of topics to display per page in the topic listing',
         'desc' => '',
         'value' => '30',
         'form' => ''),

   'max_messages' =>
      array(
         'title' => 'Multi-page threaded mode starts at how many replies?',
         'desc' => 'Once the number or replies reach this limit, the program
                    will automatically kick into expanded mode.',
         'value' => '20',
         'form' => ''),

   'subject_length_max' =>
      array(
         'title' => 'Maximum number of characters allowed in the subject field',
         'desc' => 'This is a soft limit: any characters beyond this limit will be truncated when
                    the subject is displayed.<br /> The actual hard limit
                    is 200, the number of characters stored in the database.',
         'value' => '55',
         'form' => ''),

   'display_caption' =>
      array(
         'title' => 'Display caption below the subjects in the topic listing?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'caption_length' =>
      array(
         'title' => 'If caption is on, specify the number of characters to display for the caption.',
         'desc' => '',
         'value' => '150',
         'form' => ''),

   'use_hot_image' =>
      array(
         'title' => 'How many replies are needed to use flaming images? (0 is off)',
         'desc' => '',
         'value' => '0',
         'form' => ''),



   'level_max' =>
      array(
         'title' => 'Number of message levels',
         'desc' => '',
         'value' => '20',
         'form' => ''),

   'message_indent' =>
      array(
         'title' => 'Indent message to indicate message level? (only in threaded mode)',
         'desc' => 'If \'yes\', the message tables will be indented from the
                    left side of the page to indicate their respective levels.',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'toc_threshold' =>
      array(
         'title' => 'Table of contents threshold',
         'desc' => '',
         'value' => '5',
         'form' => ''),

   'message_layout_style' =>
      array(
         'title' => 'Message layout style',
         'desc' => '',
         'value' => 'dcf',
         'form' => 'select|dcf|classic|ubb|0'),

   'quote_style' =>
      array(
         'title' => 'Quoted text style',
         'desc' => '',
         'value' => 'dcf',
         'form' => 'select|dcf|ubb|0'),

   'url_linking' =>
      array(
         'title' => 'Automatically link URLs in the messages?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'show_post_count' =>
      array(
         'title' => 'Show user post counts in the messages?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),



   'show_orig_mesg' =>
      array(
         'title' => 'Show original message in the post form?',
         'desc' => '',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'textarea_rows' =>
      array(
         'title' => 'Number of rows for text edit box',
         'desc' => '',
         'value' => '20',
         'form' => ''),

   'textarea_cols' =>
      array(
         'title' => 'Number of columns for text edit box',
         'desc' => '',
         'value' => '70',
         'form' => ''),

   'quote_wrap' =>
      array(
         'title' => 'Number of columns to wrap quoted text at - should be less than setting above',
         'desc' => '',
         'value' => '62',
         'form' => ''),

   'use_graphic_emoticons' =>
      array(
         'title' => 'Allow users to embed smilies?',
         'desc' => '',
         'value' => 'yes',
         'form' => 'radio|yes|no|0'),

   'show_emoticons_on_forms' =>
      array(
         'title' => 'Display smilie table in the post form?',
         'desc' => '',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'use_calendar' =>
      array(
         'title' => 'Enable events calendar?',
         'desc' => '',
         'value' => 'no',
         'form' => 'radio|yes|no|0'),

   'cal_allow_everyone' =>
      array(
         'title' => 'Calendar option: Allow anyone to post events?',
         'desc' => 'If this option is set to "yes", anyone can post events to the events calendar.
                    If this option is set to "no", then only registered users will be able to
                    add to the events calendar.',
         'value' => 'no',
         'form' => 'radio|yes|no|0')      



);

$setup_var_types = array(

      'time_zone' => '1',
      'date_format' => '1',
      'language' => '1',

      'auth_check_referer' => '2',
      'session_duration' => '2',
      'auth_allow_password_remembering' => '2',
      'auth_allow_account_mod' => '2',
      'auth_allow_password_mod' => '2',
      'auth_allow_retrieve_password' => '2',
      'auth_alert' => '2',
      'hide_private' => '2',
      'auth_bad_word_list' => '2',
      'display_ip_address' => '2',
      'ip_blocking' => '2',
      'ip_blocking_level' => '2',

      'auth_admin_email_address' => '3',
      'admin_signature' => '3',
      'name_length_max' => '3',
      'auth_allow_registration' => '3',
      'auth_register_via_email' => '3',
      'auth_default_group' => '3',
      'auth_bad_emails' => '3',
      'auth_activate_user_on_registration' => '3',
      'auth_notify_admin_on_registration' => '3',
      'auth_notify_user_on_activation' => '3',
      'email_to_admin' => '3',
      'email_to_mod' => '3',

      'auto_prune_forum_log' => '4',
      'auto_prune_ip_log' => '4',
      'table_width' => '4',
      'read_count' => '4',
      'announcement_display_mode' => '4',
      'display_newest_user' => '4',
      'display_num_users' => '4',
      'display_whos_online' => '4',
      'team_icon' => '4',
      'moderator_icon' => '4',
      'admin_icon' => '4',
      'inactive_user_label' => '4',
      'inactive_user_icon' => '4',
      'guest_label' => '4',
      'guest_icon' => '4',

      'file_upload' => '5',
      'file_upload_size' => '5',
      'file_upload_limit' => '5',
      'edit_allowed' => '5',
      'edit_time_out' => '5',
      'html_allowed' => '5',
      'image_allowed' => '5',
      'subscription' => '5',
      'auto_send_subscription' => '5',
      'email_notification' => '5',
      'allow_email_to_friend' => '5',
      'allow_disable_profile' => '5',
      'allow_disable_inbox' => '5',
      'allow_disable_email' => '5',
      'user_rating' => '5',
      'allow_disable_user_rating' => '5',
      'topic_rating' => '5',
      'allow_anyone_to_rate_topic' => '5',
      'topic_rating_threshold' => '5',
      'allow_avatar' => '5',
      'allow_remote_avatar' => '5',
      'allow_polls' => '5',
      'deny_poll_everyone' => '5',

      'expand_conference' => '6',
      'make_fully_threaded_list_default' => '6',
      'messages_per_page' => '6',
      'use_icons' => '6',
      'use_text' => '6',
      'default_days' => '6',
      'mesg_max' => '6',
      'max_messages' => '6',
      'subject_length_max' => '6',
      'display_caption' => '6',
      'caption_length' => '6',
      'use_hot_image' => '6',

      'level_max' => '7',
      'message_indent' => '7',
      'toc_threshold' => '7',
      'message_layout_style' => '7',
      'quote_style' => '7',
      'url_linking' => '7',
      'show_post_count' => '7',

      'show_orig_mesg' => '8',
      'textarea_rows' => '8',
      'textarea_cols' => '8',
      'quote_wrap' => '8',
      'use_graphic_emoticons' => '8',
      'show_emoticons_on_forms' => '8',

      'use_calendar' => '9',
      'cal_allow_everyone' => '9'
);


$setting_type = array(
       '1' => 'time_date',
       '2' => 'security',
       '3' => 'email_registration',
       '4' => 'general',
       '5' => 'user_option',
       '6' => 'forum_setting',
       '7' => 'topic_setting',
       '8' => 'user_input',
       '9' => 'modules'
);

?>
