<?php
//
//
// time_zone.php
//
// DCForum+ Version 1.27
// September 30, 2009
//
//
//    This file is part of DCForum+
//
//    DCForum+ is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    DCForum+ is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with DCForum+; if not, write to the Free Software
//    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
//
//
//
//
// 	$Id: time_zone.php,v 1.2 2005/04/03 04:26:25 david Exp $	
//
// array for time zone
//
$time_zone = array(

   '1' => array(
      'country' => '',
      'location' => 'GMT',
      'offset' => '0') ,
   '2' => array(
      'country' => 'Afghanistan',
      'location' => 'Kãbol',
      'offset' => '4.5') ,
   '3' => array(
      'country' => 'Albania',
      'location' => 'Tiranë',
      'offset' => '1') ,
   '4' => array(
      'country' => 'Algeria',
      'location' => 'Algiers',
      'offset' => '1') ,
   '5' => array(
      'country' => 'Angola',
      'location' => 'Luanda',
      'offset' => '1') ,
   '6' => array(
      'country' => 'Argentina',
      'location' => 'Buenos Aires',
      'offset' => '-3') ,
   '7' => array(
      'country' => 'Armenia',
      'location' => 'Jerevan',
      'offset' => '3') ,
   '9' => array(
      'country' => 'Australia',
      'location' => 'Adelaide',
      'offset' => '9.5') ,
   '11' => array(
      'country' => 'Australia',
      'location' => 'Brisbane',
      'offset' => '10') ,
   '10' => array(
      'country' => 'Australia',
      'location' => 'Darwin',
      'offset' => '9.5') ,
   '12' => array(
      'country' => 'Australia',
      'location' => 'Hobart',
      'offset' => '10') ,
   '13' => array(
      'country' => 'Australia',
      'location' => 'Melbourne',
      'offset' => '10') ,
   '8' => array(
      'country' => 'Australia',
      'location' => 'Perth',
      'offset' => '8') ,
   '14' => array(
      'country' => 'Australia',
      'location' => 'Sydney',
      'offset' => '10') ,
   '15' => array(
      'country' => 'Australia',
      'location' => 'Victoria',
      'offset' => '10') ,
   '16' => array(
      'country' => 'Austria',
      'location' => 'Vienna',
      'offset' => '1') ,
   '17' => array(
      'country' => 'Azerbaijan',
      'location' => 'Baku',
      'offset' => '4') ,
   '18' => array(
      'country' => 'Bahamas',
      'location' => 'Nassau',
      'offset' => '-5') ,
   '19' => array(
      'country' => 'Bahrain',
      'location' => 'Al Manamah',
      'offset' => '3') ,
   '20' => array(
      'country' => 'Bangladesh',
      'location' => 'Dhaka',
      'offset' => '6') ,
   '21' => array(
      'country' => 'Barbados',
      'location' => 'Bridgetown',
      'offset' => '-4') ,
   '22' => array(
      'country' => 'Belgium',
      'location' => 'Brussels',
      'offset' => '1') ,
   '23' => array(
      'country' => 'Belize',
      'location' => 'Belmopan',
      'offset' => '-6') ,
   '24' => array(
      'country' => 'Benin',
      'location' => 'Cotonou',
      'offset' => '1') ,
   '25' => array(
      'country' => 'Bermuda',
      'location' => 'Hamilton',
      'offset' => '-4') ,
   '26' => array(
      'country' => 'Bolivia',
      'location' => 'La Paz',
      'offset' => '-4') ,
   '27' => array(
      'country' => 'Bosna i Hercegovina',
      'location' => 'Sarajevo',
      'offset' => '1') ,
   '28' => array(
      'country' => 'Botswana',
      'location' => 'Gaborone',
      'offset' => '2') ,
   '30' => array(
      'country' => 'Brazil',
      'location' => 'Central Brazil',
      'offset' => '-4') ,
   '31' => array(
      'country' => 'Brazil',
      'location' => 'Rio de Janeiro',
      'offset' => '-3') ,
   '29' => array(
      'country' => 'Brazil',
      'location' => 'West Brazil',
      'offset' => '-5') ,
   '32' => array(
      'country' => 'Brunei Darussalam',
      'location' => 'Bandar Seri Begawan',
      'offset' => '8') ,
   '33' => array(
      'country' => 'Bulgaria',
      'location' => 'Sofia',
      'offset' => '2') ,
   '34' => array(
      'country' => 'Burkina Faso',
      'location' => 'Ouagadougou',
      'offset' => '0') ,
   '35' => array(
      'country' => 'Burma',
      'location' => 'Rangoon',
      'offset' => '6.5') ,
   '36' => array(
      'country' => 'Burundi',
      'location' => 'Bujumbura',
      'offset' => '2') ,
   '37' => array(
      'country' => 'Cameroon',
      'location' => 'Yaoundé',
      'offset' => '1') ,
   '43' => array(
      'country' => 'Canada',
      'location' => 'Atlantic Canada',
      'offset' => '-4') ,
   '40' => array(
      'country' => 'Canada',
      'location' => 'Central Canada',
      'offset' => '-6') ,
   '42' => array(
      'country' => 'Canada',
      'location' => 'Eastern Canada',
      'offset' => '-5') ,
   '39' => array(
      'country' => 'Canada',
      'location' => 'Mountain Canada',
      'offset' => '-7') ,
   '44' => array(
      'country' => 'Canada',
      'location' => 'Newfoundland',
      'offset' => '-3.5') ,
   '38' => array(
      'country' => 'Canada',
      'location' => 'Pacific Canada',
      'offset' => '-8') ,
   '41' => array(
      'country' => 'Canada',
      'location' => 'Saskatchewan',
      'offset' => '-6') ,
   '45' => array(
      'country' => 'Cape Verde',
      'location' => 'Praia',
      'offset' => '-2') ,
   '46' => array(
      'country' => 'Cayman Islands',
      'location' => 'Georgetown',
      'offset' => '-5') ,
   '47' => array(
      'country' => 'Central African Republic',
      'location' => 'Bangui',
      'offset' => '1') ,
   '48' => array(
      'country' => 'Chad',
      'location' => 'N. Djamena',
      'offset' => '1') ,
   '49' => array(
      'country' => 'Chile',
      'location' => 'Santiago',
      'offset' => '-4') ,
   '50' => array(
      'country' => 'China',
      'location' => 'Beijing',
      'offset' => '8') ,
   '51' => array(
      'country' => 'China',
      'location' => 'Hong Kong',
      'offset' => '8') ,
   '52' => array(
      'country' => 'Colombia',
      'location' => 'Bogota',
      'offset' => '-5') ,
   '53' => array(
      'country' => 'Comoros',
      'location' => 'Moroni',
      'offset' => '3') ,
   '56' => array(
      'country' => 'Congo, Democratic Republic of',
      'location' => 'Kasai',
      'offset' => '2') ,
   '55' => array(
      'country' => 'Congo, Democratic Republic of',
      'location' => 'Kinshasa',
      'offset' => '1') ,
   '54' => array(
      'country' => 'Congo',
      'location' => 'Brazzaville',
      'offset' => '1') ,
   '57' => array(
      'country' => 'Costa Rica',
      'location' => 'San José',
      'offset' => '-6') ,
   '58' => array(
      'country' => 'Croatia',
      'location' => 'Split',
      'offset' => '1') ,
   '59' => array(
      'country' => 'Cuba',
      'location' => 'Havana',
      'offset' => '-5') ,
   '60' => array(
      'country' => 'Cyprus',
      'location' => 'Nicosia',
      'offset' => '2') ,
   '61' => array(
      'country' => 'Czech Republic',
      'location' => 'Prague',
      'offset' => '1') ,
   '62' => array(
      'country' => 'Danmark',
      'location' => 'Copenhagen',
      'offset' => '1') ,
   '63' => array(
      'country' => 'Djibouti',
      'location' => 'Djibouti city',
      'offset' => '3') ,
   '64' => array(
      'country' => 'Dom. Republic',
      'location' => 'Santo Domingo',
      'offset' => '-4') ,
   '65' => array(
      'country' => 'Ecuador',
      'location' => 'Quito',
      'offset' => '-5') ,
   '66' => array(
      'country' => 'Egypt',
      'location' => 'Cairo',
      'offset' => '2') ,
   '67' => array(
      'country' => 'El Salvador',
      'location' => 'San Salvador',
      'offset' => '-6') ,
   '68' => array(
      'country' => 'England',
      'location' => 'London',
      'offset' => '0') ,
   '69' => array(
      'country' => 'Equatorial Guinea',
      'location' => 'Malabo',
      'offset' => '1') ,
   '70' => array(
      'country' => 'Eritrea',
      'location' => 'Asmara',
      'offset' => '3') ,
   '71' => array(
      'country' => 'Estonia',
      'location' => 'Tallinn',
      'offset' => '2') ,
   '72' => array(
      'country' => 'Ethiopia',
      'location' => 'Adis Abeba',
      'offset' => '3') ,
   '73' => array(
      'country' => 'Fiji',
      'location' => 'Suva',
      'offset' => '12') ,
   '74' => array(
      'country' => 'Finland',
      'location' => 'Helsinki',
      'offset' => '2') ,
   '75' => array(
      'country' => 'France',
      'location' => 'Paris',
      'offset' => '1') ,
   '76' => array(
      'country' => 'Gabon',
      'location' => 'Libreville',
      'offset' => '1') ,
   '77' => array(
      'country' => 'Gambia',
      'location' => 'Banjul',
      'offset' => '0') ,
   '78' => array(
      'country' => 'Georgia',
      'location' => 'Tibilisi',
      'offset' => '5') ,
   '79' => array(
      'country' => 'Germany',
      'location' => 'Berlin',
      'offset' => '1') ,
   '80' => array(
      'country' => 'Ghana',
      'location' => 'Accra',
      'offset' => '0') ,
   '81' => array(
      'country' => 'Greece',
      'location' => 'Athens',
      'offset' => '2') ,
   '82' => array(
      'country' => 'Grenada',
      'location' => 'St. George\'s',
      'offset' => '-4') ,
   '83' => array(
      'country' => 'Guatemala',
      'location' => 'Guatemala City',
      'offset' => '-6') ,
   '84' => array(
      'country' => 'Guinea',
      'location' => 'Conakry',
      'offset' => '0') ,
   '85' => array(
      'country' => 'Guinea-Bissau',
      'location' => 'Bissau',
      'offset' => '0') ,
   '86' => array(
      'country' => 'Guyana',
      'location' => 'Georgetown',
      'offset' => '-4') ,
   '87' => array(
      'country' => 'Haiti',
      'location' => 'Port-au-Prince',
      'offset' => '-5') ,
   '88' => array(
      'country' => 'Honduras',
      'location' => 'Tegucigalpa',
      'offset' => '-6') ,
   '89' => array(
      'country' => 'Hungary',
      'location' => 'Budapest',
      'offset' => '1') ,
   '90' => array(
      'country' => 'Iceland',
      'location' => 'Reykjavik',
      'offset' => '0') ,
   '91' => array(
      'country' => 'India',
      'location' => 'New Delhi',
      'offset' => '5.5') ,
   '93' => array(
      'country' => 'Indonesia',
      'location' => 'Cent. Indonesia',
      'offset' => '8') ,
   '94' => array(
      'country' => 'Indonesia',
      'location' => 'East Indonesia',
      'offset' => '9') ,
   '92' => array(
      'country' => 'Indonesia',
      'location' => 'Sumatra',
      'offset' => '7') ,
   '95' => array(
      'country' => 'Iran',
      'location' => 'Tehran',
      'offset' => '3.5') ,
   '96' => array(
      'country' => 'Iraq',
      'location' => 'Baghdad',
      'offset' => '3') ,
   '97' => array(
      'country' => 'Ireland',
      'location' => 'Dublin',
      'offset' => '0') ,
   '98' => array(
      'country' => 'Israel',
      'location' => 'Jerusalem',
      'offset' => '2') ,
   '99' => array(
      'country' => 'Italy',
      'location' => 'Rome',
      'offset' => '1') ,
   '100' => array(
      'country' => 'Ivory Coast',
      'location' => 'Yamoussoukro',
      'offset' => '-1') ,
   '101' => array(
      'country' => 'Jamaica',
      'location' => 'Kingston',
      'offset' => '-5') ,
   '102' => array(
      'country' => 'Japan',
      'location' => 'Tokyo',
      'offset' => '9') ,
   '103' => array(
      'country' => 'Jordan',
      'location' => 'Amman',
      'offset' => '2') ,
   '104' => array(
      'country' => 'Kazakhstan',
      'location' => 'Alma-Ata',
      'offset' => '6') ,
   '105' => array(
      'country' => 'Kenya',
      'location' => 'Nairobi',
      'offset' => '3') ,
   '106' => array(
      'country' => 'Kirghiz S. S. R.',
      'location' => 'Frunze',
      'offset' => '5') ,
   '107' => array(
      'country' => 'Korea, Dem. Rep.',
      'location' => 'Pyongyang',
      'offset' => '9') ,
   '108' => array(
      'country' => 'Korea, Republic',
      'location' => 'Seoul',
      'offset' => '9') ,
   '109' => array(
      'country' => 'Kuwait',
      'location' => 'Al-Kuwayt',
      'offset' => '3') ,
   '110' => array(
      'country' => 'Laos',
      'location' => 'Vientiane',
      'offset' => '7') ,
   '111' => array(
      'country' => 'Latvia',
      'location' => 'Riga',
      'offset' => '2') ,
   '112' => array(
      'country' => 'Lebanon',
      'location' => 'Beirut',
      'offset' => '2') ,
   '113' => array(
      'country' => 'Lesotho',
      'location' => 'Maseru',
      'offset' => '2') ,
   '114' => array(
      'country' => 'Liberia',
      'location' => 'Monrovia',
      'offset' => '0') ,
   '115' => array(
      'country' => 'Libya',
      'location' => 'Tripoli',
      'offset' => '2') ,
   '116' => array(
      'country' => 'Liechtenstein',
      'location' => 'Vaduz',
      'offset' => '1') ,
   '117' => array(
      'country' => 'Lithuania',
      'location' => 'Vilnius',
      'offset' => '2') ,
   '118' => array(
      'country' => 'Luxembourg',
      'location' => 'Luxembourg',
      'offset' => '1') ,
   '119' => array(
      'country' => 'Macau',
      'location' => 'Macau',
      'offset' => '8') ,
   '120' => array(
      'country' => 'Macedonia',
      'location' => 'Skopje',
      'offset' => '1') ,
   '121' => array(
      'country' => 'Madagascar',
      'location' => 'Antananarivo',
      'offset' => '3') ,
   '122' => array(
      'country' => 'Malawi',
      'location' => 'Lilongwe',
      'offset' => '2') ,
   '123' => array(
      'country' => 'Malaysia',
      'location' => 'Kuala Lumpur',
      'offset' => '8') ,
   '124' => array(
      'country' => 'Mali',
      'location' => 'Bamako',
      'offset' => '0') ,
   '125' => array(
      'country' => 'Malta',
      'location' => 'Valletta',
      'offset' => '1') ,
   '126' => array(
      'country' => 'Marshall Islands',
      'location' => 'Eniwetok Atoll',
      'offset' => '-12') ,
   '127' => array(
      'country' => 'Marshall Islands',
      'location' => 'Kwajalein Atoll',
      'offset' => '-12') ,
   '128' => array(
      'country' => 'Mauritania',
      'location' => 'Nouakchott',
      'offset' => '0') ,
   '129' => array(
      'country' => 'Mauritius',
      'location' => 'Port Louis',
      'offset' => '4') ,
   '135' => array(
      'country' => 'Mexico',
      'location' => 'Baja California Norte',
      'offset' => '-6') ,
   '131' => array(
      'country' => 'Mexico',
      'location' => 'Baja California Sur',
      'offset' => '-7') ,
   '130' => array(
      'country' => 'Mexico',
      'location' => 'Central',
      'offset' => '-8') ,
   '136' => array(
      'country' => 'Mexico',
      'location' => 'Mexico City',
      'offset' => '-6') ,
   '132' => array(
      'country' => 'Mexico',
      'location' => 'Nayarit',
      'offset' => '-7') ,
   '137' => array(
      'country' => 'Mexico',
      'location' => 'Quintana Roo',
      'offset' => '-5') ,
   '133' => array(
      'country' => 'Mexico',
      'location' => 'Sinaloa',
      'offset' => '-7') ,
   '134' => array(
      'country' => 'Mexico',
      'location' => 'Sonora',
      'offset' => '-7') ,
   '138' => array(
      'country' => 'Midway Island',
      'location' => '',
      'offset' => '-11') ,
   '139' => array(
      'country' => 'Moldova Republic',
      'location' => 'Kishinev',
      'offset' => '2') ,
   '141' => array(
      'country' => 'Mongolia',
      'location' => 'Centr. Mongolia',
      'offset' => '8') ,
   '142' => array(
      'country' => 'Mongolia',
      'location' => 'East Mongolia',
      'offset' => '9') ,
   '140' => array(
      'country' => 'Mongolia',
      'location' => 'West Mongolia',
      'offset' => '7') ,
   '143' => array(
      'country' => 'Morocco',
      'location' => 'Rabat',
      'offset' => '0') ,
   '144' => array(
      'country' => 'Mozambique',
      'location' => 'Maputo',
      'offset' => '2') ,
   '145' => array(
      'country' => 'Myanmar',
      'location' => 'Rangoon',
      'offset' => '6.5') ,
   '146' => array(
      'country' => 'Namibia',
      'location' => 'Windhoek',
      'offset' => '2') ,
   '147' => array(
      'country' => 'Nepal',
      'location' => 'Kathmandu',
      'offset' => '5.5') ,
   '148' => array(
      'country' => 'Netherland',
      'location' => 'Amsterdam',
      'offset' => '1') ,
   '149' => array(
      'country' => 'New Zealand',
      'location' => 'Wellington',
      'offset' => '12') ,
   '150' => array(
      'country' => 'Nicaragua',
      'location' => 'Managua',
      'offset' => '-6') ,
   '151' => array(
      'country' => 'Niger',
      'location' => 'Niamey',
      'offset' => '1') ,
   '152' => array(
      'country' => 'Nigeria',
      'location' => 'Lagos',
      'offset' => '1') ,
   '153' => array(
      'country' => 'Norway',
      'location' => 'Oslo',
      'offset' => '1') ,
   '154' => array(
      'country' => 'Oman',
      'location' => 'Muskat',
      'offset' => '4') ,
   '155' => array(
      'country' => 'Pakistan',
      'location' => 'Islamabad',
      'offset' => '5') ,
   '156' => array(
      'country' => 'Palestine',
      'location' => 'Abu Dis',
      'offset' => '2') ,
   '157' => array(
      'country' => 'Panama',
      'location' => 'Panama',
      'offset' => '-5') ,
   '158' => array(
      'country' => 'Papua New Guinea',
      'location' => 'Port Moresby',
      'offset' => '10') ,
   '159' => array(
      'country' => 'Paraguay',
      'location' => 'Asuncion',
      'offset' => '-4') ,
   '160' => array(
      'country' => 'Peru',
      'location' => 'Lima',
      'offset' => '-5') ,
   '161' => array(
      'country' => 'Philippines',
      'location' => 'Manila',
      'offset' => '8') ,
   '162' => array(
      'country' => 'Poland',
      'location' => 'Warsaw',
      'offset' => '1') ,
   '163' => array(
      'country' => 'Portugal',
      'location' => 'Lisbon',
      'offset' => '0') ,
   '164' => array(
      'country' => 'Puerto Rico',
      'location' => 'San Juan',
      'offset' => '-4') ,
   '165' => array(
      'country' => 'Qatar',
      'location' => 'Doha',
      'offset' => '3') ,
   '166' => array(
      'country' => 'Réunion',
      'location' => 'Saint-Denis',
      'offset' => '4') ,
   '167' => array(
      'country' => 'Romania',
      'location' => 'Bucharest',
      'offset' => '2') ,
   '180' => array(
      'country' => 'Russia',
      'location' => 'Anadyr',
      'offset' => '13') ,
   '175' => array(
      'country' => 'Russia',
      'location' => 'Irkutsk',
      'offset' => '8') ,
   '168' => array(
      'country' => 'Russia',
      'location' => 'Kaliningrad',
      'offset' => '2') ,
   '179' => array(
      'country' => 'Russia',
      'location' => 'Kamchatka',
      'offset' => '12') ,
   '174' => array(
      'country' => 'Russia',
      'location' => 'Krasnoyarsk',
      'offset' => '7') ,
   '178' => array(
      'country' => 'Russia',
      'location' => 'Magadan',
      'offset' => '11') ,
   '169' => array(
      'country' => 'Russia',
      'location' => 'Moscow',
      'offset' => '3') ,
   '172' => array(
      'country' => 'Russia',
      'location' => 'Novosibirsk',
      'offset' => '6') ,
   '173' => array(
      'country' => 'Russia',
      'location' => 'Omsk',
      'offset' => '6') ,
   '170' => array(
      'country' => 'Russia',
      'location' => 'Samara',
      'offset' => '4') ,
   '177' => array(
      'country' => 'Russia',
      'location' => 'Vladivostok',
      'offset' => '10') ,
   '176' => array(
      'country' => 'Russia',
      'location' => 'Yakutsk',
      'offset' => '9') ,
   '171' => array(
      'country' => 'Russia',
      'location' => 'Yekaterinburg',
      'offset' => '5') ,
   '181' => array(
      'country' => 'Rwanda',
      'location' => 'Kigali',
      'offset' => '2') ,
   '182' => array(
      'country' => 'Samoa',
      'location' => 'Apia',
      'offset' => '-11') ,
   '183' => array(
      'country' => 'Saudi Arabia',
      'location' => 'Riyadh',
      'offset' => '3') ,
   '184' => array(
      'country' => 'Scotland',
      'location' => 'Glasgow',
      'offset' => '0') ,
   '185' => array(
      'country' => 'Senegal',
      'location' => 'Dakar',
      'offset' => '0') ,
   '186' => array(
      'country' => 'Serbia',
      'location' => 'Belgrade',
      'offset' => '1') ,
   '187' => array(
      'country' => 'Seychelles',
      'location' => 'Victoria',
      'offset' => '4') ,
   '188' => array(
      'country' => 'Sierra Leone',
      'location' => 'Freetown',
      'offset' => '0') ,
   '189' => array(
      'country' => 'Sinapore',
      'location' => 'Singapore',
      'offset' => '8') ,
   '190' => array(
      'country' => 'Slovakia',
      'location' => 'Bratislava',
      'offset' => '1') ,
   '191' => array(
      'country' => 'Slovenia',
      'location' => 'Ljubljana',
      'offset' => '1') ,
   '192' => array(
      'country' => 'Somalia',
      'location' => 'Mogadishu',
      'offset' => '3') ,
   '193' => array(
      'country' => 'South Africa',
      'location' => 'Johannesburg',
      'offset' => '2') ,
   '194' => array(
      'country' => 'South Korea',
      'location' => 'Seoul',
      'offset' => '9') ,
   '195' => array(
      'country' => 'Spain',
      'location' => 'Canary Islands',
      'offset' => '1') ,
   '196' => array(
      'country' => 'Spain',
      'location' => 'Madrid',
      'offset' => '1') ,
   '197' => array(
      'country' => 'Sri Lanka',
      'location' => 'Colombo',
      'offset' => '6') ,
   '198' => array(
      'country' => 'Sudan',
      'location' => 'Khartoum',
      'offset' => '2') ,
   '199' => array(
      'country' => 'Suriname',
      'location' => 'Paramaribo',
      'offset' => '-3.5') ,
   '200' => array(
      'country' => 'Swaziland',
      'location' => 'Mbabane',
      'offset' => '2') ,
   '201' => array(
      'country' => 'Sweden',
      'location' => 'Stockholm',
      'offset' => '1') ,
   '202' => array(
      'country' => 'Switzerland',
      'location' => 'Geneva',
      'offset' => '1') ,
   '203' => array(
      'country' => 'Syria',
      'location' => 'Damascus',
      'offset' => '2') ,
   '204' => array(
      'country' => 'Taiwan',
      'location' => 'Taipei',
      'offset' => '8') ,
   '205' => array(
      'country' => 'Tajikistan',
      'location' => 'Duanbe',
      'offset' => '5') ,
   '206' => array(
      'country' => 'Tanzania',
      'location' => 'Dar es Salaam',
      'offset' => '3') ,
   '207' => array(
      'country' => 'Thailand',
      'location' => 'Bangkok',
      'offset' => '7') ,
   '208' => array(
      'country' => 'Togo',
      'location' => 'Lomé',
      'offset' => '0') ,
   '209' => array(
      'country' => 'Trinidad and Tobago',
      'location' => 'Port of Spain',
      'offset' => '-4') ,
   '210' => array(
      'country' => 'Tunisia',
      'location' => 'Tunis',
      'offset' => '1') ,
   '211' => array(
      'country' => 'Turkey',
      'location' => 'Istanbul',
      'offset' => '2') ,
   '212' => array(
      'country' => 'Turkmenistan',
      'location' => 'Achabad',
      'offset' => '5') ,
   '222' => array(
      'country' => 'Uganda',
      'location' => 'Kampala',
      'offset' => '3') ,
   '223' => array(
      'country' => 'Ukraine',
      'location' => 'Kyiv',
      'offset' => '2') ,
   '224' => array(
      'country' => 'United Arab Emirates',
      'location' => 'Abu Dhabi',
      'offset' => '4') ,
   '225' => array(
      'country' => 'Uruguay',
      'location' => 'Montevideo',
      'offset' => '-3') ,
   '215' => array(
      'country' => 'USA',
      'location' => 'Alaska',
      'offset' => '-9') ,
   '213' => array(
      'country' => 'USA',
      'location' => 'Aleutian',
      'offset' => '-10') ,
   '217' => array(
      'country' => 'USA',
      'location' => 'Arizona',
      'offset' => '-7') ,
   '219' => array(
      'country' => 'USA',
      'location' => 'Central ',
      'offset' => '-6') ,
   '220' => array(
      'country' => 'USA',
      'location' => 'Eastern ',
      'offset' => '-5') ,

   '214' => array(
      'country' => 'USA',
      'location' => 'Hawaii',
      'offset' => '-10') ,
   '221' => array(
      'country' => 'USA',
      'location' => 'Indiana East',
      'offset' => '-5') ,
   '218' => array(
      'country' => 'USA',
      'location' => 'Mountain ',
      'offset' => '-7') ,
   '216' => array(
      'country' => 'USA',
      'location' => 'Pacific ',
      'offset' => '-8') ,
   '226' => array(
      'country' => 'Uzbekistan',
      'location' => 'Tekent',
      'offset' => '5') ,
   '227' => array(
      'country' => 'Vanuatu',
      'location' => 'Port Vila',
      'offset' => '11') ,
   '228' => array(
      'country' => 'Venezuela',
      'location' => 'Caracas',
      'offset' => '-4') ,
   '229' => array(
      'country' => 'Vietnam',
      'location' => 'Saigon',
      'offset' => '7') ,
   '230' => array(
      'country' => 'Wales',
      'location' => 'Cardiff',
      'offset' => '0') ,
   '231' => array(
      'country' => 'Yeman',
      'location' => 'Aden',
      'offset' => '3') ,
   '232' => array(
      'country' => 'Yugoslavia',
      'location' => 'Belgrade',
      'offset' => '1') ,
   '233' => array(
      'country' => 'Zambia',
      'location' => 'Lusaka',
      'offset' => '2') ,
   '234' => array(
      'country' => 'Zimbabwe',
      'location' => 'Harare',
      'offset' => '2'),

   '250' => array(
      'country' => 'USA',
      'location' => 'Eastern (EDT)',
      'offset' => '-5') 


);

?>